### ISSUE TITLE
virtualenv directory and .DS_Store should not be versioned

### ISSUE THREAD

**Issue by dellelce** [Jflick58/DepressionAI#9]
it is good practice not to version virtulenv directory, also .DS_Store is a Mac thing that is not really part of the code.

if you really need to keep your venv in the same path as your code I would add a README.md in it and version it git add -f   and put venv in .gitignore.

I would suggest remove the content with git filter-branch.

**Comment by Jflick58** [comment]
Thank you for bringing this to my attention. I just deleted those directories/files. 

-- Justin
